# Generated by `aontu render` from model.aon. Do not edit.
#
# The routes are written out rather than drawn with `resources`, because
# the API's paths are the reference's and not Rails' pluralised
# defaults: its collection is `/api/planet`, singular, and its
# parameter is `:planet_id` rather than `:id`.

Rails.application.routes.draw do
  root "planets#index"

  # Planets
  get "/planets", to: "planets#index", as: :planets
  get "/planets/:planet_id", to: "planets#show", as: :planet

  # Moons
  get "/planets/:planet_id/moons", to: "moons#index", as: :planet_moons
  get "/planets/:planet_id/moons/:moon_id", to: "moons#show", as: :planet_moon

  # Planets, the API
  get "/api/planet", to: "api/planets#index"
  post "/api/planet", to: "api/planets#create"
  get "/api/planet/:planet_id", to: "api/planets#show"
  put "/api/planet/:planet_id", to: "api/planets#update"
  delete "/api/planet/:planet_id", to: "api/planets#destroy"
  post "/api/planet/:planet_id/terraform", to: "api/planets#terraform"
  post "/api/planet/:planet_id/forbid", to: "api/planets#forbid"

  # Moons, the API
  get "/api/planet/:planet_id/moon", to: "api/moons#index"
  post "/api/planet/:planet_id/moon", to: "api/moons#create"
  get "/api/planet/:planet_id/moon/:moon_id", to: "api/moons#show"
  put "/api/planet/:planet_id/moon/:moon_id", to: "api/moons#update"
  delete "/api/planet/:planet_id/moon/:moon_id", to: "api/moons#destroy"
end
