# Generated by `aontu render` from model.aon. Do not edit.

class CreateMoons < ActiveRecord::Migration[8.0]
  def change
    # THE API SUPPLIES THE ID. Every record is addressed by a name the
    # client chose -- `earth`, `luna` -- so the primary key is a string
    # the caller sets rather than a counter this table keeps.
    create_table :moons, id: :string do |t|
      t.string :name
      t.string :planet_id
      t.string :kind
      t.float :diameter
      t.timestamps
    end
    add_index :moons, :planet_id
  end
end
