# Generated by `aontu render` from model.aon. Do not edit.

class CreatePlanets < ActiveRecord::Migration[8.0]
  def change
    # THE API SUPPLIES THE ID. Every record is addressed by a name the
    # client chose -- `earth`, `luna` -- so the primary key is a string
    # the caller sets rather than a counter this table keeps.
    create_table :planets, id: :string do |t|
      t.string :name
      t.string :kind
      t.float :diameter
      t.string :terraform_state
      t.string :forbid_state
      t.string :forbid_reason
      t.timestamps
    end
  end
end
