"use strict";
/* Copyright (c) 2020-2023 Richard Rodger and other contributors, MIT License */
Object.defineProperty(exports, "__esModule", { value: true });
const node_test_1 = require("node:test");
const lang_1 = require("../dist/lang");
const unify_1 = require("../dist/unify");
const MapVal_1 = require("../dist/val/MapVal");
const code_1 = require("@hapi/code");
const op_1 = require("../dist/op/op");
let lang = new lang_1.Lang();
let PL = lang.parse.bind(lang);
let P = (x, ctx) => PL(x, ctx);
let PA = (x, ctx) => x.map(s => PL(s, ctx));
(0, node_test_1.describe)('op', () => {
    (0, node_test_1.it)('happy', () => {
        (0, code_1.expect)(op_1.unite.name).equal('unite');
        (0, code_1.expect)(op_1.disjunct.name).equal('disjunct');
    });
    (0, node_test_1.it)('unite-scalar-val', () => {
        let U = makeUnite();
        (0, code_1.expect)(U('nil nil')).equal('nil');
        // EXPANSION: expect(unite(ctx, P('nil'), P('nil')).canon).equal('nil')
        (0, code_1.expect)(U('undef nil')).equal('nil');
        // EXPANSION: expect(unite(ctx, undefined, P('nil')).canon).equal('nil')
        (0, code_1.expect)(U('nil')).equal('nil');
        // EXPANSION: expect(unite(ctx, P('nil')).canon).equal('nil')
        (0, code_1.expect)(U('')).equal('nil');
        // EXPANSION: expect(unite(ctx).canon).equal('nil')
        (0, code_1.expect)(U('top          ')).equal('top');
        (0, code_1.expect)(U('undef  top   ')).equal('top');
        (0, code_1.expect)(U('top    top   ')).equal('top');
        (0, code_1.expect)(U('top    1     ')).equal('1');
        (0, code_1.expect)(U('1      top   ')).equal('1');
        (0, code_1.expect)(U('top    nil   ')).equal('nil');
        (0, code_1.expect)(U('nil    top   ')).equal('nil');
        (0, code_1.expect)(U('1            ')).equal('1');
        (0, code_1.expect)(U('undef  1     ')).equal('1');
        (0, code_1.expect)(U('1      1     ')).equal('1');
        (0, code_1.expect)(U('1      2     ')).equal('nil');
        (0, code_1.expect)(U('2      1     ')).equal('nil');
        (0, code_1.expect)(U('1      "a"   ')).equal('nil');
        (0, code_1.expect)(U('"a"    1     ')).equal('nil');
        (0, code_1.expect)(U('1      nil   ')).equal('nil');
        (0, code_1.expect)(U('nil    1     ')).equal('nil');
        (0, code_1.expect)(U('true         ')).equal('true');
        (0, code_1.expect)(U('undef  true  ')).equal('true');
        (0, code_1.expect)(U('true   true  ')).equal('true');
        (0, code_1.expect)(U('true   2     ')).equal('nil');
        (0, code_1.expect)(U('2      true  ')).equal('nil');
        (0, code_1.expect)(U('true  "a"    ')).equal('nil');
        (0, code_1.expect)(U('"a"    true  ')).equal('nil');
        (0, code_1.expect)(U('true   false ')).equal('nil');
        (0, code_1.expect)(U('false  true  ')).equal('nil');
        (0, code_1.expect)(U('true   nil   ')).equal('nil');
        (0, code_1.expect)(U('nil    true  ')).equal('nil');
        (0, code_1.expect)(U('false        ')).equal('false');
        (0, code_1.expect)(U('undef  false ')).equal('false');
        (0, code_1.expect)(U('false  false ')).equal('false');
        (0, code_1.expect)(U('false  2     ')).equal('nil');
        (0, code_1.expect)(U('2      false ')).equal('nil');
        (0, code_1.expect)(U('false  "a"   ')).equal('nil');
        (0, code_1.expect)(U('"a"    false ')).equal('nil');
        (0, code_1.expect)(U('false  nil   ')).equal('nil');
        (0, code_1.expect)(U('nil    false ')).equal('nil');
        (0, code_1.expect)(U('"a"          ')).equal('"a"');
        (0, code_1.expect)(U('undef  "a"   ')).equal('"a"');
        (0, code_1.expect)(U('"a"    "a"   ')).equal('"a"');
        (0, code_1.expect)(U('"a"    "b"   ')).equal('nil');
        (0, code_1.expect)(U('"b"    "a"   ')).equal('nil');
        (0, code_1.expect)(U('"a"    nil   ')).equal('nil');
        (0, code_1.expect)(U('nil    "a"   ')).equal('nil');
    });
    (0, node_test_1.it)('unite-scalar-type', () => {
        let U = makeUnite();
        (0, code_1.expect)(U('number')).equal('number');
        (0, code_1.expect)(U('number  number')).equal('number');
        (0, code_1.expect)(U('number  top')).equal('number');
        (0, code_1.expect)(U('top     number')).equal('number');
        (0, code_1.expect)(U('number  nil')).equal('nil');
        (0, code_1.expect)(U('nil     number')).equal('nil');
        (0, code_1.expect)(U('number  integer')).equal('integer');
        (0, code_1.expect)(U('integer number')).equal('integer');
        (0, code_1.expect)(U('number  string')).equal('nil');
        (0, code_1.expect)(U('string  number')).equal('nil');
        (0, code_1.expect)(U('number  boolean')).equal('nil');
        (0, code_1.expect)(U('boolean number')).equal('nil');
        (0, code_1.expect)(U('number  1')).equal('1');
        (0, code_1.expect)(U('1       number')).equal('1');
        (0, code_1.expect)(U('number  1.1')).equal('1.1');
        (0, code_1.expect)(U('1.1     number')).equal('1.1');
        (0, code_1.expect)(U('number  "a"')).equal('nil');
        (0, code_1.expect)(U('"a"     number')).equal('nil');
        (0, code_1.expect)(U('number  true')).equal('nil');
        (0, code_1.expect)(U('true    number')).equal('nil');
        (0, code_1.expect)(U('number  false')).equal('nil');
        (0, code_1.expect)(U('false   number')).equal('nil');
        (0, code_1.expect)(U('integer')).equal('integer');
        (0, code_1.expect)(U('integer  integer')).equal('integer');
        (0, code_1.expect)(U('integer  top')).equal('integer');
        (0, code_1.expect)(U('top      integer')).equal('integer');
        (0, code_1.expect)(U('integer  nil')).equal('nil');
        (0, code_1.expect)(U('nil      integer')).equal('nil');
        (0, code_1.expect)(U('integer  string')).equal('nil');
        (0, code_1.expect)(U('string   integer')).equal('nil');
        (0, code_1.expect)(U('integer  boolean')).equal('nil');
        (0, code_1.expect)(U('boolean  integer')).equal('nil');
        (0, code_1.expect)(U('integer  1')).equal('1');
        (0, code_1.expect)(U('1        integer')).equal('1');
        (0, code_1.expect)(U('integer  "a"')).equal('nil');
        (0, code_1.expect)(U('"a"      integer')).equal('nil');
        (0, code_1.expect)(U('integer  true')).equal('nil');
        (0, code_1.expect)(U('true     integer')).equal('nil');
        (0, code_1.expect)(U('integer  false')).equal('nil');
        (0, code_1.expect)(U('false    integer')).equal('nil');
        (0, code_1.expect)(U('string')).equal('string');
        (0, code_1.expect)(U('string   string')).equal('string');
        (0, code_1.expect)(U('string   top')).equal('string');
        (0, code_1.expect)(U('top      string')).equal('string');
        (0, code_1.expect)(U('string   nil')).equal('nil');
        (0, code_1.expect)(U('nil      string')).equal('nil');
        (0, code_1.expect)(U('string   boolean')).equal('nil');
        (0, code_1.expect)(U('boolean  string')).equal('nil');
        (0, code_1.expect)(U('string   1')).equal('nil');
        (0, code_1.expect)(U('1        string')).equal('nil');
        (0, code_1.expect)(U('string   "a"')).equal('"a"');
        (0, code_1.expect)(U('"a"      string')).equal('"a"');
        (0, code_1.expect)(U('string   true')).equal('nil');
        (0, code_1.expect)(U('true     string')).equal('nil');
        (0, code_1.expect)(U('string   false')).equal('nil');
        (0, code_1.expect)(U('false    string')).equal('nil');
        (0, code_1.expect)(U('boolean')).equal('boolean');
        (0, code_1.expect)(U('boolean  boolean')).equal('boolean');
        (0, code_1.expect)(U('boolean  top')).equal('boolean');
        (0, code_1.expect)(U('top      boolean')).equal('boolean');
        (0, code_1.expect)(U('boolean  nil')).equal('nil');
        (0, code_1.expect)(U('nil      boolean')).equal('nil');
        (0, code_1.expect)(U('boolean  1')).equal('nil');
        (0, code_1.expect)(U('1        boolean')).equal('nil');
        (0, code_1.expect)(U('boolean  "a"')).equal('nil');
        (0, code_1.expect)(U('"a"      boolean')).equal('nil');
        (0, code_1.expect)(U('boolean  true')).equal('true');
        (0, code_1.expect)(U('true     boolean')).equal('true');
        (0, code_1.expect)(U('boolean  false')).equal('false');
        (0, code_1.expect)(U('false    boolean')).equal('false');
    });
    (0, node_test_1.it)('unite-map-scalar', () => {
        let U = makeUnite();
        (0, code_1.expect)(U('{a:1}')).equal('{"a":1}');
        (0, code_1.expect)(U('undef  {a:1}')).equal('{"a":1}');
        (0, code_1.expect)(U('{a:1}  {a:1}')).equal('{"a":1}');
        (0, code_1.expect)(U('{a:1}  top')).equal('{"a":1}');
        (0, code_1.expect)(U('top    {a:1}')).equal('{"a":1}');
        (0, code_1.expect)(U('{a:1}    nil')).equal('nil');
        (0, code_1.expect)(U('nil      {a:1}')).equal('nil');
        (0, code_1.expect)(U('{a:1}    1')).equal('nil');
        (0, code_1.expect)(U('1        {a:1}')).equal('nil');
        (0, code_1.expect)(U('{a:1}    "b"')).equal('nil');
        (0, code_1.expect)(U('"b"      {a:1}')).equal('nil');
        (0, code_1.expect)(U('{a:1}    true')).equal('nil');
        (0, code_1.expect)(U('true     {a:1}')).equal('nil');
        (0, code_1.expect)(U('{a:1}    false')).equal('nil');
        (0, code_1.expect)(U('false    {a:1}')).equal('nil');
        (0, code_1.expect)(U('{a:1}    number')).equal('nil');
        (0, code_1.expect)(U('number   {a:1}')).equal('nil');
        (0, code_1.expect)(U('{a:1}    integer')).equal('nil');
        (0, code_1.expect)(U('integer  {a:1}')).equal('nil');
        (0, code_1.expect)(U('{a:1}    string')).equal('nil');
        (0, code_1.expect)(U('string   {a:1}')).equal('nil');
        (0, code_1.expect)(U('{a:1}    boolean')).equal('nil');
        (0, code_1.expect)(U('boolean  {a:1}')).equal('nil');
        (0, code_1.expect)(U('{a:top}    {a:top}')).equal('{"a":top}');
        (0, code_1.expect)(U('{a:nil}    {a:nil}')).equal('{"a":nil}');
        (0, code_1.expect)(U('{a:top}    {a:nil}')).equal('{"a":nil}');
        (0, code_1.expect)(U('{a:nil}    {a:top}')).equal('{"a":nil}');
        (0, code_1.expect)(U('{a:1}      {a:nil}')).equal('{"a":nil}');
        (0, code_1.expect)(U('{a:nil}    {a:1}')).equal('{"a":nil}');
        (0, code_1.expect)(U('{a:1}      {a:top}')).equal('{"a":1}');
        (0, code_1.expect)(U('{a:top}    {a:1}')).equal('{"a":1}');
        (0, code_1.expect)(U('{a:1}      {a:2}')).equal('{"a":nil}');
        (0, code_1.expect)(U('{a:2}      {a:1}')).equal('{"a":nil}');
        (0, code_1.expect)(U('{a:1}      {a:true}')).equal('{"a":nil}');
        (0, code_1.expect)(U('{a:true}   {a:1}')).equal('{"a":nil}');
        (0, code_1.expect)(U('{a:1}      {a:false}')).equal('{"a":nil}');
        (0, code_1.expect)(U('{a:false}  {a:1}')).equal('{"a":nil}');
        (0, code_1.expect)(U('{a:number}   {a:1}')).equal('{"a":1}');
        (0, code_1.expect)(U('{a:integer}  {a:1}')).equal('{"a":1}');
        (0, code_1.expect)(U('{a:integer}  {a:1.1}')).equal('{"a":nil}');
        (0, code_1.expect)(U('{a:string}   {a:1}')).equal('{"a":nil}');
        (0, code_1.expect)(U('{a:boolean}  {a:1}')).equal('{"a":nil}');
        (0, code_1.expect)(U('{a:1}        {a:number}')).equal('{"a":1}');
        (0, code_1.expect)(U('{a:1}        {a:integer}')).equal('{"a":1}');
        (0, code_1.expect)(U('{a:1.1}      {a:integer}')).equal('{"a":nil}');
        (0, code_1.expect)(U('{a:1}        {a:string}')).equal('{"a":nil}');
        (0, code_1.expect)(U('{a:1}        {a:boolean}')).equal('{"a":nil}');
        (0, code_1.expect)(U('{a:number}   {a:"x"}')).equal('{"a":nil}');
        (0, code_1.expect)(U('{a:integer}  {a:"x"}')).equal('{"a":nil}');
        (0, code_1.expect)(U('{a:string}   {a:"x"}')).equal('{"a":"x"}');
        (0, code_1.expect)(U('{a:boolean}  {a:"x"}')).equal('{"a":nil}');
        (0, code_1.expect)(U('{a:"x"}      {a:number}')).equal('{"a":nil}');
        (0, code_1.expect)(U('{a:"x"}      {a:integer}')).equal('{"a":nil}');
        (0, code_1.expect)(U('{a:"x"}      {a:string}')).equal('{"a":"x"}');
        (0, code_1.expect)(U('{a:"x"}      {a:boolean}')).equal('{"a":nil}');
        (0, code_1.expect)(U('{a:true}     {a:number}')).equal('{"a":nil}');
        (0, code_1.expect)(U('{a:true}     {a:integer}')).equal('{"a":nil}');
        (0, code_1.expect)(U('{a:true}     {a:string}')).equal('{"a":nil}');
        (0, code_1.expect)(U('{a:true}     {a:boolean}')).equal('{"a":true}');
        (0, code_1.expect)(U('{a:number}   {a:true}')).equal('{"a":nil}');
        (0, code_1.expect)(U('{a:integer}  {a:true}')).equal('{"a":nil}');
        (0, code_1.expect)(U('{a:string}   {a:true}')).equal('{"a":nil}');
        (0, code_1.expect)(U('{a:boolean}  {a:true}')).equal('{"a":true}');
        (0, code_1.expect)(U('{a:number}   {a:false}')).equal('{"a":nil}');
        (0, code_1.expect)(U('{a:integer}  {a:false}')).equal('{"a":nil}');
        (0, code_1.expect)(U('{a:string}   {a:false}')).equal('{"a":nil}');
        (0, code_1.expect)(U('{a:boolean}  {a:false}')).equal('{"a":false}');
        (0, code_1.expect)(U('{a:false}    {a:number}')).equal('{"a":nil}');
        (0, code_1.expect)(U('{a:false}    {a:integer}')).equal('{"a":nil}');
        (0, code_1.expect)(U('{a:false}    {a:string}')).equal('{"a":nil}');
        (0, code_1.expect)(U('{a:false}    {a:boolean}')).equal('{"a":false}');
        (0, code_1.expect)(U('{a:1}        {b:2}')).equal('{"a":1,"b":2}');
        (0, code_1.expect)(U('{b:2}        {a:1}')).equal('{"b":2,"a":1}');
    });
    (0, node_test_1.it)('unite-conjunct', () => {
        let U = makeUnite();
        //expect(U('1&1')).equal('1')
        (0, code_1.expect)(U('1&number')).equal('1');
    });
});
function makeCtx(r) {
    return new unify_1.Context({ root: r || new MapVal_1.MapVal({ peg: {} }) });
}
function makeUnite(r) {
    let ctx = makeCtx(r);
    return (s) => {
        let terms = s.trim().split(/\s+/).map(x => 'undef' === x ? undefined : x);
        return (0, op_1.unite)(ctx, ...PA(terms)).canon;
    };
}
//# sourceMappingURL=op.test.js.map