# Generated by `aontu render` from model.aon. Do not edit.

class Moon < ApplicationRecord
  # THE CLIENT NAMES THE RECORD. `earth`, `luna`: the primary key is a
  # string the caller supplies, so Active Record is told which column
  # it is rather than looking for an integer counter.
  self.primary_key = "id"

  belongs_to :planet, class_name: "Planet", foreign_key: "planet_id"
  validates :diameter, presence: true
  validates :id, presence: true
  validates :kind, presence: true
  validates :name, presence: true
  validates :planet_id, presence: true
end
