# Generated by `aontu render` from model.aon. Do not edit.

class Planet < ApplicationRecord
  # THE CLIENT NAMES THE RECORD. `earth`, `luna`: the primary key is a
  # string the caller supplies, so Active Record is told which column
  # it is rather than looking for an integer counter.
  self.primary_key = "id"

  has_many :moons, class_name: "Moon", foreign_key: "planet_id", dependent: :destroy
  validates :id, presence: true
  validates :name, presence: true
  validates :kind, presence: true
  validates :diameter, presence: true
end
