/* Copyright (c) 2025 Richard Rodger, MIT License */

// Regenerate the build-time-inlined copies of the built-in aontu:
// models from the canonical tree in aontu/: ts/src/aontumodel.ts,
// go/aontumodel/ and go/aontumodel.go. Run via `make aontu`; both
// suites assert the copies are identical with the tree, so a stale copy
// fails rather than ships.

const fs = require('fs')
const path = require('path')

const root = path.join(__dirname, '..', '..')
const tree = path.join(root, 'aontu')

// EVERY .aon UNDER aontu/ IS A MODULE, named by its path without the
// extension -- aontu/render/lang/go.aon is `aontu:render/lang/go`.
// A file named after the directory holding it collapses, so
// aontu/code/code.aon is `aontu:code` and not `aontu:code/code`: a
// module that wants a folder of its own can have one without spelling
// its name twice.
function modules(dir, rel) {
  const found = []
  for (const entry of fs.readdirSync(dir, { withFileTypes: true }).sort(
    (a, b) => a.name < b.name ? -1 : 1)) {
    const at = path.join(dir, entry.name)
    const subrel = rel ? rel + '/' + entry.name : entry.name
    if (entry.isDirectory()) {
      found.push(...modules(at, subrel))
      continue
    }
    if (!entry.name.endsWith('.aon')) { continue }
    const part = subrel.slice(0, -'.aon'.length).split('/')
    if (1 < part.length && part[part.length - 1] === part[part.length - 2]) {
      part.pop()
    }
    found.push({
      name: 'aontu:' + part.join('/'),
      file: path.relative(root, at).replaceAll(path.sep, '/'),
      embed: 'aontumodel/' + subrel,
      text: fs.readFileSync(at, 'utf8')
        .replaceAll('\r\n', '\n').replaceAll('\r', '\n'),
    })
  }
  return found
}

const found = modules(tree, '').sort((a, b) => a.name < b.name ? -1 : 1)

if (0 === found.length) {
  console.error('aontu: no models under aontu/')
  process.exit(1)
}

const sources = {}
for (const m of found) { sources[m.name] = m.text }

const ts =
  '/* Copyright (c) 2025 Richard Rodger, MIT License */\n\n' +
  '// GENERATED by ts/scripts/aontu.cjs (`make aontu`) from aontu/ —\n' +
  '// DO NOT EDIT. The tree is the source;\n' +
  '// ts/test/aontumodel.test.ts asserts this copy is identical with\n' +
  '// it.\n\n' +
  'const AONTU_SCHEME = \'aontu:\'\n\n' +
  'const AONTU_SOURCES: Record<string, string> = ' +
  JSON.stringify(sources, null, 2) + '\n\n' +
  'const AONTU_MODELS: string[] = ' +
  JSON.stringify(found.map((m) => m.name), null, 2) + '\n\n' +
  'export { AONTU_SCHEME, AONTU_SOURCES, AONTU_MODELS }\n'

fs.writeFileSync(path.join(root, 'ts', 'src', 'aontumodel.ts'), ts)

// The Go half must be a committed copy: //go:embed cannot read above
// its own package directory. go/aontumodel/ mirrors aontu/ byte for
// byte -- NOT go/aontu/, which is where `go build ./cmd/aontu` drops
// its binary -- and go/aontumodel.go embeds it one file at a time, an
// embed per model rather than a directory walk, so the table costs no
// run-time parse and no unreachable error arm.
const goTree = path.join(root, 'go', 'aontumodel')
fs.rmSync(goTree, { recursive: true, force: true })
for (const m of found) {
  const at = path.join(root, 'go', m.embed)
  fs.mkdirSync(path.dirname(at), { recursive: true })
  fs.writeFileSync(at, m.text)
}

// aontu:render/lang/go -> aontuLangGo
function ident(name) {
  return 'aontu' + name.slice('aontu:'.length).split('/')
    .map((seg) => seg[0].toUpperCase() + seg.slice(1)).join('')
}

const width = found.reduce(
  (n, m) => Math.max(n, JSON.stringify(m.name).length + 1), 0)

const go =
  '/* Copyright (c) 2025 Richard Rodger, MIT License */\n\n' +
  '// GENERATED by ts/scripts/aontu.cjs (`make aontu`) from aontu/ -\n' +
  '// DO NOT EDIT. The tree is the source; go/aontumodel_test.go\n' +
  '// asserts go/aontumodel/ is identical with it.\n\n' +
  'package aontu\n\n' +
  'import _ "embed"\n\n' +
  'const aontuScheme = "aontu:"\n\n' +
  found.map((m) =>
    '//go:embed ' + m.embed + '\n' +
    'var ' + ident(m.name) + ' string\n').join('\n') + '\n' +
  'var aontuSources = map[string]string{\n' +
  found.map((m) => {
    const key = JSON.stringify(m.name) + ':'
    return '\t' + key + ' '.repeat(width - key.length + 1) + ident(m.name) + ','
  }).join('\n') + '\n}\n\n' +
  '// aontuModels names the set the scheme serves, sorted, for the\n' +
  '// not-found message: a typo in an aontu: name is refused naming the\n' +
  '// set rather than searched for on disk.\n' +
  'var aontuModels = []string{\n' +
  found.map((m) => '\t' + JSON.stringify(m.name) + ',').join('\n') + '\n}\n'

fs.writeFileSync(path.join(root, 'go', 'aontumodel.go'), go)

console.log(
  'aontu: wrote ts/src/aontumodel.ts, go/aontumodel.go and go/aontumodel/ (' +
  found.length + ' models, ' +
  found.reduce((n, m) => n + m.text.length, 0) + ' bytes)')
