/* Copyright (c) 2025 Richard Rodger, MIT License */

// Regenerate the build-time-inlined TEACHING PACK — the corpus
// `aontu help <topic>` serves (G11 phase 1): ts/src/helpdoc.ts and
// go/cmd/aontu/helpdoc/*.md, both byte-derived from docs/skill/*.md
// and grammar/aontu.abnf. Run via `make helpdoc`, which `make
// build-ts` runs for you; both suites assert the copies are identical
// with the sources, so a stale copy fails loudly.
//
// WHY A COMMITTED COPY RATHER THAN A READ AT RUN TIME. The whole
// point of the phase is an agent holding a binary and nothing else:
// a path lookup into a repository that is not there serves nobody.
// `ts/scripts/prepack.js` already stages docs/skill/ into the npm
// tarball, but a tarball is not the Go story and `node_modules/aontu/
// skill/` is not a place anything looks. Embedding is the delivery.
//
// AND WHY GENERATED RATHER THAN WRITTEN TWICE. `//go:embed` cannot
// read above its own package directory, so the Go half MUST be a
// copy inside go/cmd/aontu/ — there is no other mechanism. Given one
// copy is forced, the choice is between one generated copy asserted
// byte-identical and two hand-maintained ones that drift. This is
// the sigdecl precedent (test/spec/signature.tsv -> go/sigdecl.txt +
// ts/src/sigdecl.ts), applied to prose.

const fs = require('fs')
const path = require('path')

const root = path.join(__dirname, '..', '..')

// The corpus, in the order `aontu help` lists it. `summary` is the
// index line; it is the ONE piece of text here that is not derived,
// because an index describes the topics rather than quoting them.
const TOPICS = [
  {
    topic: 'tasks',
    summary: 'what do you want to do? — the verb for a job',
    source: 'docs/skill/tasks.md',
  },
  {
    topic: 'language',
    summary: 'the grammar card — everything the language spells, on one page',
    source: 'docs/skill/grammar-card.md',
  },
  {
    topic: 'examples',
    summary: 'the ladder — plain JSON, then one addition at a time',
    source: 'docs/skill/examples.md',
  },
  {
    topic: 'codes',
    summary: 'what a refusal means, and what to do about it',
    source: 'docs/skill/error-codes.md',
  },
  {
    topic: 'grammar',
    summary: 'the published ABNF, for a parser or a constrained decoder',
    source: 'grammar/aontu.abnf',
  },
]


// THE INIT TRIO (G11 phase 6): the known-good starting document
// `aontu init` writes. Staged the same way and for the same reason --
// both ports must write the same bytes, and the files are real,
// runnable, and tested where they live (ts/test/helpdoc.test.ts runs
// docs/skill/init/check.sh over them).
//
// `mode` is the file mode `init` creates each with: check.sh is a
// script and a scaffold that has to be chmod'ed before it runs is a
// scaffold with a step missing.
const INIT = [
  { file: 'docs/skill/init/model.aon', name: 'model.aon', mode: 0o644 },
  { file: 'docs/skill/init/data.aon', name: 'data.aon', mode: 0o644 },
  { file: 'docs/skill/init/check.sh', name: 'check.sh', mode: 0o755 },
]


// LINE ENDINGS ARE THE CHECKOUT'S BUSINESS, the rule every other gate
// in this repository states: .gitattributes pins .md to LF, and this
// normalises what did not come from a checkout so the byte-identity
// assertions compare content rather than a Windows clone.
function read(rel) {
  return fs.readFileSync(path.join(root, rel), 'utf8')
    .replaceAll('\r\n', '\n').replaceAll('\r', '\n')
}


const corpus = TOPICS.map((t) => ({ ...t, text: read(t.source) }))

// The TypeScript half: one module, the corpus inlined as data.
const init = INIT.map((f) => ({ ...f, text: read(f.file) }))

const ts =
  '/* Copyright (c) 2025 Richard Rodger, MIT License */\n\n' +
  '// GENERATED by ts/scripts/helpdoc.cjs (`make helpdoc`) from\n' +
  '// docs/skill/*.md and grammar/aontu.abnf — DO NOT EDIT. The skill\n' +
  '// sources are the source; ts/test/helpdoc.test.ts asserts this copy\n' +
  '// is identical with them.\n\n' +
  'type HelpTopic = {\n' +
  '  topic: string\n' +
  '  summary: string\n' +
  '  source: string\n' +
  '  text: string\n' +
  '}\n\n' +
  'const HELPDOC: HelpTopic[] = ' +
  JSON.stringify(corpus, null, 2) + '\n\n' +
  'type InitFile = {\n' +
  '  file: string\n' +
  '  mode: number\n' +
  '  name: string\n' +
  '  text: string\n' +
  '}\n\n' +
  'const INITDOC: InitFile[] = ' +
  JSON.stringify(init, null, 2) + '\n\n' +
  'export type { HelpTopic, InitFile }\n' +
  'export { HELPDOC, INITDOC }\n'

fs.writeFileSync(path.join(root, 'ts', 'src', 'helpdoc.ts'), ts)

// The Go half: one file per topic under go/cmd/aontu/helpdoc/, which
// is what //go:embed can reach, plus an index naming the order and
// the summaries so the two ports list topics identically.
const goDir = path.join(root, 'go', 'cmd', 'aontu', 'helpdoc')
fs.rmSync(goDir, { recursive: true, force: true })
fs.mkdirSync(goDir, { recursive: true })
// Each staged file KEEPS ITS SOURCE BASENAME, so a reader who opens
// go/cmd/aontu/helpdoc/ can see at a glance which repository file
// each one came from, and `grammar/aontu.abnf` does not arrive
// wearing a `.md` extension it has never had.
for (const t of corpus) {
  fs.writeFileSync(path.join(goDir, path.basename(t.source)), t.text)
}

// index.tsv: topic <TAB> file <TAB> summary <TAB> source, one row per
// topic, in the listing order. A TSV because this repository already
// reads one (test/spec/*.tsv) and a Go map has no order to trust.
fs.writeFileSync(
  path.join(goDir, 'index.tsv'),
  '# GENERATED by ts/scripts/helpdoc.cjs (`make helpdoc`) - DO NOT EDIT.\n' +
  '# topic\tfile\tsummary\tsource\n' +
  corpus.map((t) => [
    t.topic, path.basename(t.source), t.summary, t.source,
  ].join('\t')).join('\n') +
  '\n')

// The Go half of the init trio: one file per member under
// helpdoc/init/, plus an index carrying the name and the mode.
const initDir = path.join(goDir, 'init')
fs.mkdirSync(initDir, { recursive: true })
for (const f of init) {
  fs.writeFileSync(path.join(initDir, f.name), f.text)
}
fs.writeFileSync(
  path.join(initDir, 'index.tsv'),
  '# GENERATED by ts/scripts/helpdoc.cjs (`make helpdoc`) - DO NOT EDIT.\n' +
  '# name\tmode\tfile\n' +
  init.map((f) => [f.name, f.mode.toString(8), f.file].join('\t')).join('\n') +
  '\n')

console.log(
  'helpdoc: wrote ts/src/helpdoc.ts and go/cmd/aontu/helpdoc/ (' +
  corpus.length + ' topics, ' +
  corpus.reduce((n, t) => n + t.text.length, 0) + ' bytes)')
