/* Copyright (c) 2025 Richard Rodger, MIT License */


const fs = require('fs')
const path = require('path')

const root = path.join(__dirname, '..', '..')

// The corpus, in the order `aontu help` lists it. `summary` is the
// index line; it is the ONE piece of text here that is not derived,
// because an index describes the topics rather than quoting them.
const TOPICS = [
  {
    topic: 'tasks',
    summary: 'what do you want to do? — the verb for a job',
    source: 'docs/skill/tasks.md',
  },
  {
    topic: 'language',
    summary: 'the grammar card — everything the language spells, on one page',
    source: 'docs/skill/grammar-card.md',
  },
  {
    topic: 'examples',
    summary: 'the ladder — plain JSON, then one addition at a time',
    source: 'docs/skill/examples.md',
  },
  {
    topic: 'codes',
    summary: 'what a refusal means, and what to do about it',
    source: 'docs/skill/error-codes.md',
  },
  {
    topic: 'grammar',
    summary: 'the published ABNF, for a parser or a constrained decoder',
    source: 'grammar/aontu.abnf',
  },
]


const INIT = [
  { file: 'docs/skill/init/model.aon', name: 'model.aon', mode: 0o644 },
  { file: 'docs/skill/init/data.aon', name: 'data.aon', mode: 0o644 },
  { file: 'docs/skill/init/check.sh', name: 'check.sh', mode: 0o755 },
]


function read(rel) {
  return fs.readFileSync(path.join(root, rel), 'utf8')
    .replaceAll('\r\n', '\n').replaceAll('\r', '\n')
}


const corpus = TOPICS.map((t) => ({ ...t, text: read(t.source) }))

// The TypeScript half: one module, the corpus inlined as data.
const init = INIT.map((f) => ({ ...f, text: read(f.file) }))

const ts =
  '/* Copyright (c) 2025 Richard Rodger, MIT License */\n\n' +
  '// GENERATED by ts/scripts/helpdoc.cjs (`make helpdoc`) from\n' +
  '// docs/skill/*.md and grammar/aontu.abnf — DO NOT EDIT. The skill\n' +
  '// sources are the source; ts/test/helpdoc.test.ts asserts this copy\n' +
  '// is identical with them.\n\n' +
  'type HelpTopic = {\n' +
  '  topic: string\n' +
  '  summary: string\n' +
  '  source: string\n' +
  '  text: string\n' +
  '}\n\n' +
  'const HELPDOC: HelpTopic[] = ' +
  JSON.stringify(corpus, null, 2) + '\n\n' +
  'type InitFile = {\n' +
  '  file: string\n' +
  '  mode: number\n' +
  '  name: string\n' +
  '  text: string\n' +
  '}\n\n' +
  'const INITDOC: InitFile[] = ' +
  JSON.stringify(init, null, 2) + '\n\n' +
  'export type { HelpTopic, InitFile }\n' +
  'export { HELPDOC, INITDOC }\n'

fs.writeFileSync(path.join(root, 'ts', 'src', 'helpdoc.ts'), ts)

const goDir = path.join(root, 'go', 'cmd', 'aontu', 'helpdoc')
fs.rmSync(goDir, { recursive: true, force: true })
fs.mkdirSync(goDir, { recursive: true })
for (const t of corpus) {
  fs.writeFileSync(path.join(goDir, path.basename(t.source)), t.text)
}

// index.tsv: topic <TAB> file <TAB> summary <TAB> source, one row per
// topic, in the listing order. A TSV because this repository already
// reads one (test/spec/*.tsv) and a Go map has no order to trust.
fs.writeFileSync(
  path.join(goDir, 'index.tsv'),
  '# GENERATED by ts/scripts/helpdoc.cjs (`make helpdoc`) - DO NOT EDIT.\n' +
  '# topic\tfile\tsummary\tsource\n' +
  corpus.map((t) => [
    t.topic, path.basename(t.source), t.summary, t.source,
  ].join('\t')).join('\n') +
  '\n')

// The Go half of the init trio: one file per member under
// helpdoc/init/, plus an index carrying the name and the mode.
const initDir = path.join(goDir, 'init')
fs.mkdirSync(initDir, { recursive: true })
for (const f of init) {
  fs.writeFileSync(path.join(initDir, f.name), f.text)
}
fs.writeFileSync(
  path.join(initDir, 'index.tsv'),
  '# GENERATED by ts/scripts/helpdoc.cjs (`make helpdoc`) - DO NOT EDIT.\n' +
  '# name\tmode\tfile\n' +
  init.map((f) => [f.name, f.mode.toString(8), f.file].join('\t')).join('\n') +
  '\n')

console.log(
  'helpdoc: wrote ts/src/helpdoc.ts and go/cmd/aontu/helpdoc/ (' +
  corpus.length + ' topics, ' +
  corpus.reduce((n, t) => n + t.text.length, 0) + ' bytes)')
