# Generated by `aontu render` from model.aon. Do not edit.

module Api
  class BaseController < ActionController::API
    private

    # ONE SHAPE FOR EVERY REFUSAL. The reference answers `{error,
    # message}` with the error's own name in it, and its test 13 reads
    # both, so the envelope is part of the API rather than a detail of
    # this implementation.
    def render_error(name, status, message)
      render json: { error: name, message: message }, status: status
    end

    def not_found(entity, id)
      render_error("NotFoundError", 404, format("%s with id '%s' not found", entity, id))
    end

    def invalid(detail)
      render_error("ValidationError", 400, format("%s", detail))
    end

    def conflict(entity, id)
      render_error("ConflictError", 409, format("%s with id '%s' already exists", entity, id))
    end
  end
end
