# Generated by `aontu render` from model.aon. Do not edit.

module Api
  class MoonsController < BaseController
    before_action :scope

    def index
      render json: @scope.moons.map { |record| serialize(record) }
    end

    def show
      record = find_one
      return not_found("Moon", params[:moon_id]) if record.nil?

      render json: serialize(record)
    end

    def create
      # A CLIENT-SUPPLIED ID CAN COLLIDE. Without this the second
      # create would overwrite the first and answer 201 as though it
      # had inserted, which is the reference's own reason for the code.
      if find_by_id(params[:id])
        return conflict("Moon", params[:id])
      end

      record = build
      if record.save
        render json: serialize(record), status: :created
      else
        invalid(problems(record))
      end
    end

    def update
      record = find_one
      return not_found("Moon", params[:moon_id]) if record.nil?

      if record.update(permitted)
        render json: serialize(record)
      else
        invalid(problems(record))
      end
    end

    def destroy
      record = find_one
      return not_found("Moon", params[:moon_id]) if record.nil?

      record.destroy
      head :no_content
    end

    private

    def scope
      @scope = Planet.find_by(id: params[:planet_id])
      not_found("Planet", params[:planet_id]) if @scope.nil?
    end

    def find_one
      @scope.moons.find_by(id: params[:moon_id])
    end

    def find_by_id(id)
      @scope.moons.find_by(id: id)
    end

    def build
      @scope.moons.new(permitted)
    end

    # THE ATTRIBUTE NAME REACHES THE WIRE IN THE CASE THE MODEL WROTE
    # IT. The reference's test 14 posts a planet with no `kind` and
    # looks for that word in the message; Rails' own full messages
    # capitalise it, so the pair is spelled out here instead.
    def problems(record)
      record.errors.map { |e| "#{e.attribute} #{e.message}" }.join(", ")
    end

    def permitted
      params.permit(:id, :name, :planet_id, :kind, :diameter)
    end

    # THE WIRE NAME IS THE MODEL'S, not the column's: `terraformState`
    # over `terraform_state`, and `planet_id` either way.
    def serialize(record)
      {
        "id" => record.id,
        "name" => record.name,
        "planet_id" => record.planet_id,
        "kind" => record.kind,
        "diameter" => record.diameter,
      }
    end
  end
end
