# Generated by `aontu render` from model.aon. Do not edit.

module Api
  class PlanetsController < BaseController
    def index
      render json: Planet.all.map { |record| serialize(record) }
    end

    def show
      record = find_one
      return not_found("Planet", params[:planet_id]) if record.nil?

      render json: serialize(record)
    end

    def create
      # A CLIENT-SUPPLIED ID CAN COLLIDE. Without this the second
      # create would overwrite the first and answer 201 as though it
      # had inserted, which is the reference's own reason for the code.
      if find_by_id(params[:id])
        return conflict("Planet", params[:id])
      end

      record = build
      if record.save
        render json: serialize(record), status: :created
      else
        invalid(problems(record))
      end
    end

    def update
      record = find_one
      return not_found("Planet", params[:planet_id]) if record.nil?

      if record.update(permitted)
        render json: serialize(record)
      else
        invalid(problems(record))
      end
    end

    def destroy
      record = find_one
      return not_found("Planet", params[:planet_id]) if record.nil?

      record.destroy
      head :no_content
    end

    def forbid
      record = find_one
      return not_found("Planet", params[:planet_id]) if record.nil?

      state = "allowed"
      state = "forbidden" if params[:forbid]
      record.forbid_reason = params[:forbid] ? params[:why] : nil
      record.forbid_state = state
      record.save!
      render json: { ok: true, state: state }
    end

    def terraform
      record = find_one
      return not_found("Planet", params[:planet_id]) if record.nil?

      state = "idle"
      state = record.terraform_state if record.terraform_state.present?
      state = "idle" if params[:stop]
      state = "terraforming" if params[:start]
      record.terraform_state = state
      record.save!
      render json: { ok: true, state: state }
    end

    private

    def find_one
      Planet.find_by(id: params[:planet_id])
    end

    def find_by_id(id)
      Planet.find_by(id: id)
    end

    def build
      Planet.new(permitted)
    end

    # THE ATTRIBUTE NAME REACHES THE WIRE IN THE CASE THE MODEL WROTE
    # IT. The reference's test 14 posts a planet with no `kind` and
    # looks for that word in the message; Rails' own full messages
    # capitalise it, so the pair is spelled out here instead.
    def problems(record)
      record.errors.map { |e| "#{e.attribute} #{e.message}" }.join(", ")
    end

    def permitted
      params.permit(:diameter, :id, :kind, :name)
    end

    # THE WIRE NAME IS THE MODEL'S, not the column's: `terraformState`
    # over `terraform_state`, and `planet_id` either way.
    def serialize(record)
      {
        "diameter" => record.diameter,
        "forbidReason" => record.forbid_reason,
        "forbidState" => record.forbid_state,
        "id" => record.id,
        "kind" => record.kind,
        "name" => record.name,
        "terraformState" => record.terraform_state,
      }
    end
  end
end
