# Generated by `aontu render` from model.aon. Do not edit.
#
# The data is the reference's own: `ref/solar.data.json`, included by
# the model rather than copied, so these rows and the ones the
# reference app serves cannot drift apart.

Moon.delete_all
Planet.delete_all

# Planets
Planet.create!(id: "earth", name: "Earth", kind: "rock", diameter: 12756)
Planet.create!(id: "jupiter", name: "Jupiter", kind: "gas", diameter: 142984)
Planet.create!(id: "mars", name: "Mars", kind: "rock", diameter: 6792)
Planet.create!(id: "mercury", name: "Mercury", kind: "rock", diameter: 4879)
Planet.create!(id: "neptune", name: "Neptune", kind: "gas", diameter: 49528)
Planet.create!(id: "saturn", name: "Saturn", kind: "gas", diameter: 120536)
Planet.create!(id: "uranus", name: "Uranus", kind: "gas", diameter: 51118)
Planet.create!(id: "venus", name: "Venus", kind: "rock", diameter: 12104)

# Moons
Moon.create!(id: "callisto", name: "Callisto", planet_id: "jupiter", kind: "ice", diameter: 4820)
Moon.create!(id: "deimos", name: "Deimos", planet_id: "mars", kind: "rock", diameter: 12)
Moon.create!(id: "despina", name: "Despina", planet_id: "neptune", kind: "rock", diameter: 150)
Moon.create!(id: "dione", name: "Dione", planet_id: "saturn", kind: "ice", diameter: 1120)
Moon.create!(id: "enceladus", name: "Enceladus", planet_id: "saturn", kind: "ice", diameter: 499)
Moon.create!(id: "europa", name: "Europa", planet_id: "jupiter", kind: "ice", diameter: 3122)
Moon.create!(id: "galatea", name: "Galatea", planet_id: "neptune", kind: "rock", diameter: 180)
Moon.create!(id: "ganymede", name: "Ganymede", planet_id: "jupiter", kind: "ice", diameter: 5270)
Moon.create!(id: "io", name: "Io", planet_id: "jupiter", kind: "rock", diameter: 3636)
Moon.create!(id: "larissa", name: "Larissa", planet_id: "neptune", kind: "rock", diameter: 194)
Moon.create!(id: "luna", name: "Luna", planet_id: "earth", kind: "rock", diameter: 3475)
Moon.create!(id: "mimas", name: "Mimas", planet_id: "saturn", kind: "ice", diameter: 397)
Moon.create!(id: "naiad", name: "Naiad", planet_id: "neptune", kind: "rock", diameter: 66)
Moon.create!(id: "nereid", name: "Nereid", planet_id: "neptune", kind: "ice", diameter: 340)
Moon.create!(id: "phobos", name: "Phobos", planet_id: "mars", kind: "rock", diameter: 22)
Moon.create!(id: "proteus", name: "Proteus", planet_id: "neptune", kind: "rock", diameter: 420)
Moon.create!(id: "rhea", name: "Rhea", planet_id: "saturn", kind: "ice", diameter: 1528)
Moon.create!(id: "tethys", name: "Tethys", planet_id: "saturn", kind: "ice", diameter: 1060)
Moon.create!(id: "thalassa", name: "Thalassa", planet_id: "neptune", kind: "rock", diameter: 80)
Moon.create!(id: "titan", name: "Titan", planet_id: "saturn", kind: "ice", diameter: 5149)
Moon.create!(id: "triton", name: "Triton", planet_id: "neptune", kind: "ice", diameter: 2706)
