# Generated by `aontu render` from model.aon. Do not edit.

class MoonsController < ApplicationController
  before_action :scope

  def index
    @records = @scope.moons.order(:id)
  end

  def show
    @record = @scope.moons.find_by(id: params[:moon_id])
    head :not_found if @record.nil?
  end

  private

  def scope
    @scope = Planet.find_by(id: params[:planet_id])
    head :not_found if @scope.nil?
  end
end
