# Generated by `aontu render` from model.aon. Do not edit.

class PlanetsController < ApplicationController
  def index
    @records = Planet.all.order(:id)
  end

  def show
    @record = Planet.find_by(id: params[:planet_id])
    head :not_found if @record.nil?
  end
end
