/* Copyright (c) 2025 Richard Rodger, MIT License */

// GENERATED by ts/scripts/aontu.cjs (`make aontu`) from aontu/ -
// DO NOT EDIT. The tree is the source; go/aontumodel_test.go
// asserts go/aontumodel/ is identical with it.

package aontu

import _ "embed"

const aontuScheme = "aontu:"

//go:embed aontumodel/code/code.aon
var aontuCode string

//go:embed aontumodel/render/render.aon
var aontuRender string

//go:embed aontumodel/render/lang/go.aon
var aontuRenderLangGo string

//go:embed aontumodel/render/lang/markdown.aon
var aontuRenderLangMarkdown string

//go:embed aontumodel/render/lang/text.aon
var aontuRenderLangText string

//go:embed aontumodel/render/lang/typescript.aon
var aontuRenderLangTypescript string

//go:embed aontumodel/system/system.aon
var aontuSystem string

//go:embed aontumodel/view/view.aon
var aontuView string

var aontuSources = map[string]string{
	"aontu:code":                   aontuCode,
	"aontu:render":                 aontuRender,
	"aontu:render/lang/go":         aontuRenderLangGo,
	"aontu:render/lang/markdown":   aontuRenderLangMarkdown,
	"aontu:render/lang/text":       aontuRenderLangText,
	"aontu:render/lang/typescript": aontuRenderLangTypescript,
	"aontu:system":                 aontuSystem,
	"aontu:view":                   aontuView,
}

// aontuModels names the set the scheme serves, sorted, for the
// not-found message: a typo in an aontu: name is refused naming the
// set rather than searched for on disk.
var aontuModels = []string{
	"aontu:code",
	"aontu:render",
	"aontu:render/lang/go",
	"aontu:render/lang/markdown",
	"aontu:render/lang/text",
	"aontu:render/lang/typescript",
	"aontu:system",
	"aontu:view",
}
