/* Copyright (c) 2025 Richard Rodger, MIT License */

// GENERATED by ts/scripts/aontu.cjs (`make aontu`) from aontu/ -
// DO NOT EDIT. The tree is the source; go/aontumodel_test.go
// asserts go/aontumodel/ is identical with it.

package aontu

import _ "embed"

const aontuScheme = "aontu:"

//go:embed aontumodel/code/code.aon
var aontuCode string

//go:embed aontumodel/lang/go/go.aon
var aontuLangGo string

//go:embed aontumodel/lang/markdown/markdown.aon
var aontuLangMarkdown string

//go:embed aontumodel/lang/text/text.aon
var aontuLangText string

//go:embed aontumodel/lang/typescript/typescript.aon
var aontuLangTypescript string

//go:embed aontumodel/profile/profile.aon
var aontuProfile string

//go:embed aontumodel/system/system.aon
var aontuSystem string

//go:embed aontumodel/view/view.aon
var aontuView string

var aontuSources = map[string]string{
	"aontu:code":            aontuCode,
	"aontu:lang/go":         aontuLangGo,
	"aontu:lang/markdown":   aontuLangMarkdown,
	"aontu:lang/text":       aontuLangText,
	"aontu:lang/typescript": aontuLangTypescript,
	"aontu:profile":         aontuProfile,
	"aontu:system":          aontuSystem,
	"aontu:view":            aontuView,
}

// aontuModels names the set the scheme serves, sorted, for the
// not-found message: a typo in an aontu: name is refused naming the
// set rather than searched for on disk.
var aontuModels = []string{
	"aontu:code",
	"aontu:lang/go",
	"aontu:lang/markdown",
	"aontu:lang/text",
	"aontu:lang/typescript",
	"aontu:profile",
	"aontu:system",
	"aontu:view",
}
