/* Copyright (c) 2025 Richard Rodger, MIT License */

package main

// The Go twin of the mod-tool cases in ts/test/mod.test.ts. Both
// subcommands are LOCAL, and both are file operations, so they are
// proved here rather than in the shared suite — which has no mode for
// "run a command in a directory". The two ports were diffed over the
// same sixteen invocations (text and JSON, every usage error, the
// lockfile bytes and the vendor tree): identical but for the version
// field, G2 phase 3's standing carve-out.

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	aontu "github.com/rjrodger/aontu/go"
)

const modToolSource = "name: string\nport: *8080 | integer\n"

func modRun(args ...string) (string, string, int) {
	var out, errw bytes.Buffer
	code := run(append([]string{"mod"}, args...),
		strings.NewReader(""), &out, &errw, false)
	return out.String(), errw.String(), code
}

// modProject builds a project with the given dep block.
func modProject(t *testing.T, dep string) string {
	t.Helper()
	dir := t.TempDir()
	modWrite(t, filepath.Join(dir, "mod.aon"),
		"mod: {path: \"corp.example/app\"}\ndep: {"+dep+"}\n")
	return dir
}

func modVendorTree(t *testing.T, dir, path string, files map[string]string) {
	t.Helper()
	p := filepath.Join(append([]string{dir, "aon_vendor"},
		strings.Split(path, "/")...)...)
	if err := os.MkdirAll(p, 0o755); nil != err {
		t.Fatal(err)
	}
	for name, src := range files {
		modWrite(t, filepath.Join(p, name), src)
	}
}

func modWrite(t *testing.T, file, src string) {
	t.Helper()
	if err := os.WriteFile(file, []byte(src), 0o600); nil != err {
		t.Fatal(err)
	}
}

func TestModTidyWritesCanonicalLockfile(t *testing.T) {
	dir := modProject(t, "\"corp.example/schemas/service@1\": {v: \"1.4.2\"}")
	modVendorTree(t, dir, "corp.example/schemas/service@1", map[string]string{
		"mod.aon":     "mod: {path: \"corp.example/schemas/service\", main: \"service.aon\"}\n",
		"service.aon": modToolSource,
	})

	out, errw, code := modRun("tidy", dir)
	if 0 != code {
		t.Fatalf("tidy = %d: %s", code, errw)
	}
	if !strings.Contains(out, "verdict: ok") {
		t.Fatalf("want ok:\n%s", out)
	}

	data, err := os.ReadFile(filepath.Join(dir, "mod-lock.aon"))
	if nil != err {
		t.Fatal(err)
	}
	lock := string(data)
	// A HEADER the file's own reader skips, then ONE canonical line —
	// sorted keys, no spaces — which is also the JSON the resolver reads
	// a pin back from.
	if !strings.HasPrefix(lock, "# mod-lock.aon (generated by") {
		t.Fatalf("want the generated-file header:\n%s", lock)
	}
	line := strings.Split(lock, "\n")[1]
	v, _ := aontu.New().Unify(modToolSource)
	want := "{\"lock\":{\"corp.example/schemas/service@1\":{\"canon\":\"" +
		aontu.CanonHash(v) + "\",\"oci\":\"\",\"v\":\"1.4.2\"}}}"
	if line != want {
		t.Fatalf("lock line\n want: %s\n got:  %s", want, line)
	}
	var parsed map[string]any
	if err := json.Unmarshal([]byte(line), &parsed); nil != err {
		t.Fatalf("the canonical line must be JSON: %v", err)
	}
}

func TestModTidySelectsMaximumOfMinima(t *testing.T) {
	// MINIMUM VERSION SELECTION: the project asks for 1.2.0 of geo and
	// the module it depends on asks for 1.10.0, so 1.10.0 is selected —
	// and 1.10.0 is above 1.2.0 by NUMBER, which string order gets
	// wrong.
	dir := modProject(t,
		"\"corp.example/s@1\": {v: \"1.2.0\"}, \"corp.example/geo@1\": {v: \"1.2.0\"}")
	modVendorTree(t, dir, "corp.example/s@1", map[string]string{
		"mod.aon": "mod: {path: \"corp.example/s\"}\n" +
			"dep: {\"corp.example/geo@1\": {v: \"1.10.0\"}}\n",
		"main.aon": modToolSource,
	})
	modVendorTree(t, dir, "corp.example/geo@1", map[string]string{
		"mod.aon":  "mod: {path: \"corp.example/geo\"}\n",
		"main.aon": "region: string\n",
	})

	out, errw, code := modRun("tidy", dir)
	if 0 != code {
		t.Fatalf("tidy = %d: %s", code, errw)
	}
	if !strings.Contains(out, "corp.example/geo@1 1.10.0 aon1-") {
		t.Fatalf("want geo at 1.10.0:\n%s", out)
	}
}

func TestModVersionOrderIsNumeric(t *testing.T) {
	for _, c := range []struct {
		a, b string
		want int
	}{
		{"1.10.0", "1.9.0", 1},
		// A part the shorter version does not have is ZERO.
		{"1.2", "1.2.0", 0},
		{"1.2.0", "1.2.0", 0},
		// A part that is not a number sorts as text, AFTER every
		// number: a pre-release tag is below no version and above none.
		{"1.2.0", "1.2.rc", -1},
		{"1.2.rc", "1.2.0", 1},
		{"1.2.rc", "1.2.beta", 1},
	} {
		if got := aontu.VersionCompare(c.a, c.b); got != c.want {
			t.Fatalf("VersionCompare(%q,%q) = %d, want %d", c.a, c.b, got, c.want)
		}
	}
}

func TestModTidyRefusesToLockWhatItCannotSee(t *testing.T) {
	// A lockfile naming a module nobody has is a lie, so no lockfile is
	// written at all.
	dir := modProject(t, "\"corp.example/absent@1\": {v: \"1.0.0\"}")
	out, _, code := modRun("tidy", dir)
	if 1 != code {
		t.Fatalf("want 1, got %d:\n%s", code, out)
	}
	if !strings.Contains(out, "corp.example/absent@1: not fetched") {
		t.Fatalf("want the fetch instruction:\n%s", out)
	}
	if _, err := os.Stat(filepath.Join(dir, "mod-lock.aon")); nil == err {
		t.Fatal("no lockfile may be written")
	}
}

func TestModVendorMaterialisesTheClosure(t *testing.T) {
	// From the CACHE, keyed by the hash the lockfile pins: that is what
	// content-addressed means, and why `vendor` needs a lockfile while
	// `tidy` needs a store.
	dir := modProject(t, "")
	v, _ := aontu.New().Unify(modToolSource)
	hash := aontu.CanonHash(v)

	xdg := filepath.Join(dir, "xdg")
	cachedir := filepath.Join(xdg, "aontu", "mod", hash)
	if err := os.MkdirAll(cachedir, 0o755); nil != err {
		t.Fatal(err)
	}
	modWrite(t, filepath.Join(cachedir, "mod.aon"),
		"mod: {path: \"corp.example/schemas/service\", main: \"service.aon\"}\n")
	modWrite(t, filepath.Join(cachedir, "service.aon"), modToolSource)
	modWrite(t, filepath.Join(dir, "mod-lock.aon"),
		"# mod-lock.aon (generated by `aontu mod tidy`; do not edit)\n"+
			"{\"lock\":{\"corp.example/schemas/service@1\":{\"canon\":\""+hash+
			"\",\"oci\":\"\",\"v\":\"1.4.2\"}}}\n")

	t.Setenv("XDG_CACHE_HOME", xdg)
	out, errw, code := modRun("vendor", dir)
	if 0 != code {
		t.Fatalf("vendor = %d: %s\n%s", code, errw, out)
	}
	if _, err := os.Stat(filepath.Join(dir, "aon_vendor", "corp.example",
		"schemas", "service@1", "service.aon")); nil != err {
		t.Fatalf("want the module materialised: %v", err)
	}
}

func TestModVendorReportsWhatNoStoreHas(t *testing.T) {
	dir := modProject(t, "")
	modWrite(t, filepath.Join(dir, "mod-lock.aon"),
		"{\"lock\":{\"nope@1\":{\"canon\":\"x\",\"oci\":\"\",\"v\":\"1\"},"+
			"\"not-a-module\":{\"canon\":\"y\",\"oci\":\"\",\"v\":\"1\"}}}\n")
	out, _, code := modRun("vendor", dir)
	if 1 != code {
		t.Fatalf("want 1, got %d:\n%s", code, out)
	}
	for _, want := range []string{"nope@1: not fetched", "not-a-module: not fetched"} {
		if !strings.Contains(out, want) {
			t.Fatalf("want %q:\n%s", want, out)
		}
	}
}

func TestModNetworkHalfSaysWhichHalf(t *testing.T) {
	// `get` and `publish` are named rather than left to fall out as an
	// unknown subcommand: a reader of the design will type them, and
	// deserves to be told which half is missing.
	for _, sub := range []string{"get", "publish"} {
		if _, errw, code := modRun(sub); 2 != code ||
			!strings.Contains(errw, "needs a registry client") {
			t.Fatalf("mod %s = %d: %s", sub, code, errw)
		}
	}
}

func TestModArguments(t *testing.T) {
	if out, _, code := modRun("--help"); 0 != code ||
		!strings.Contains(out, "aontu mod") {
		t.Fatalf("--help = %d:\n%s", code, out)
	}
	for _, args := range [][]string{{}, {"nope"}, {"tidy", "a", "b"}} {
		if _, errw, code := modRun(args...); 2 != code ||
			!strings.Contains(errw, "needs tidy or vendor") {
			t.Fatalf("%v = %d: %s", args, code, errw)
		}
	}
	if _, errw, code := modRun("--format", "yaml", "tidy"); 2 != code ||
		!strings.Contains(errw, "text or json") {
		t.Fatalf("bad format = %d: %s", code, errw)
	}
	if _, errw, code := modRun("--format"); 2 != code ||
		!strings.Contains(errw, "text or json") {
		t.Fatalf("missing format value = %d: %s", code, errw)
	}
	if _, errw, code := modRun("--nope", "tidy"); 2 != code ||
		!strings.Contains(errw, "unknown mod option") {
		t.Fatalf("bad option = %d: %s", code, errw)
	}
}

func TestModTidyJSONIsTheReport(t *testing.T) {
	dir := modProject(t, "\"corp.example/schemas/service@1\": {v: \"1.4.2\"}")
	modVendorTree(t, dir, "corp.example/schemas/service@1", map[string]string{
		"mod.aon":     "mod: {path: \"corp.example/schemas/service\", main: \"service.aon\"}\n",
		"service.aon": modToolSource,
	})

	out, _, code := modRun("tidy", "--format", "json", dir)
	if 0 != code {
		t.Fatalf("tidy json = %d:\n%s", code, out)
	}
	var report struct {
		Aontu struct {
			Verb string `json:"verb"`
		} `json:"aontu"`
		Lock []struct {
			Mod string `json:"mod"`
		} `json:"lock"`
		Missing []string `json:"missing"`
		Verdict string   `json:"verdict"`
	}
	if err := json.Unmarshal([]byte(out), &report); nil != err {
		t.Fatalf("not JSON: %v\n%s", err, out)
	}
	if "mod tidy" != report.Aontu.Verb || "ok" != report.Verdict ||
		1 != len(report.Lock) ||
		"corp.example/schemas/service@1" != report.Lock[0].Mod {
		t.Fatalf("bad report: %+v", report)
	}
}
